### PR TITLE
Make compatible with kitspace.org

### PR DESCRIPTION
**Pull request by kasbah**
Hey, neat project! I made it compatible with [kitspace.org](https://kitspace.org) by adding a bill of materials (cribbed Digikey parts from #3), plotting the gerbers (one day Kitspace will do this automatically :disappointed:  ) and adding a [kitspace.yaml manifest file](https://github.com/kitspace/kitspace#kitspaceyaml-format).

If you are up for adding it then just merge this. [Here is a preview](http://add-open-book.preview.kitspace.org/boards/github.com/kitspace-forks/The-Open-Book) of what it would look like. It would make it easier for others to re-build the PCB and the Kitspace page will be automatically kept up to date with this repo going forward (though it can take up to 24hrs to propagate).

### CODE REVIEW

**Comment by kasbah** [comment]
Hey, would you like a Kitspace page for your project?

**Comment by joeycastillo** [comment]
Sorry I dropped the ball on this issue! Yes, definitely; I had been waiting to get the design 100% squared away before doing a Kitspace page, but the E-Book Wing is there, and the last Open Book revision should be good to go very shortly (I want to test one alternate version of a part that's available on DigiKey, to save folks the headache of ordering it from overseas). 

[Here's the BOM for the Wing](https://github.com/joeycastillo/The-Open-Book/files/4767367/E-Book.Wing.BOM.txt); this is just what I've been printing out when I send folks the board, but it does have the DigiKey part numbers for every part on there. If there's an easy way for me to cross reference that to other suppliers let me know and I'll add that too. 

Kitspace is really awesome, and totally aligned with my hopes for this project; thank you for reaching out about it!

**Comment by kasbah** [comment]
That's great Joey! You should be able to use that BOM as is and you will get a 1-click Digikey link on the page. (You will need to add the path to `bom:` in the `kitspace.yaml`. )

If you want to spend more time on the BOM and add other suppliers then I you could use the [bom-builder](https://github.com/kitspace/bom-builder/). I can give you access to a hosted version, we need to pay for the Octopart API requests so we keep these a semi-secret. Please send me an email (kaspar@kitspace.org) or join [our chat](https://riot.im/app/#/room/#kitspace:matrix.org) and I'll send you the link.

Eventually we want to integrate the bom-builder functionality itself into Kitspace properly, so people can use it from the page and select the distributor parts from the manufacturer parts directly, but that's another matter. 

Once we add the page it should keep in sync with your repo with only 3-10 minute delay now by the way (not 24hrs anymore).

**Comment by kasbah** [comment]
Thanks for merging, it's up! https://kitspace.org/boards/github.com/joeycastillo/the-open-book/

If you want to add another design from this repository later you will want to modify the `kitspace.yaml` to use the [multi field](https://github.com/kitspace/kitspace#the-multi-field). Also please ping me if you do that, as I should add a URL redirect.

**Pull request merged**
